apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallerique-deployment
  labels:
    app: gallerique
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gallerique
  template:
    metadata:
      labels:
        app: gallerique
    spec:
      containers:
      - name: gallerique
        image: ${DOCKER_USERNAME}/gallerique:${DOCKER_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: gallerique-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: gallerique-secrets
              key: db-port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: gallerique-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gallerique-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gallerique-secrets
              key: db-name
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always 